config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'main_page#index'

  post 'reload-section'  => 'sections#reload'

  resource :exercise_settings, path: 'kryteria' do
  end

  scope module: :random_exercise, path: :losowe do
    resource :random_exercises, path: 'cwiczenie' do
      post '/sprawdz', action: :check, as: :check
    end
  end

  get 'autocomplete/verbs' => 'verbs#all'

  scope module: :personal do
    resource :exercise_sets, path: 'zestawy-cwiczeniowe' do
      get '/', action: :index, as: :index
      get '/cwicz/:id', action: :train, as: :train
      post '/cwicz/:id', action: :check, as: :check
      post '/zapisz-postepy', action: :save_progress, as: :save_progress
    end
  end

end

app/models/active_hash_where.rb
module ActiveHashWhere
  def where_in(options)
    retrieve_elements(:&, options)
  end

  def where_not_in(options)
    retrieve_elements(:-, options)
  end

  private

  def retrieve_elements(relation, options)
    result = all
    options.each do |key, values|
      result = result.send(relation, all.select{ |v| values.include?(v.send(key))})
    end
    result
  end
end

app/models/conjugation/form.rb
module Conjugation
  class Form < ActiveYaml::Base
    include ActiveHash::Associations
    extend ActiveHashWhere

    belongs_to :tense, class_name: 'Conjugation::Tense'
    belongs_to :verb, class_name: 'Conjugation::Verb'
    belongs_to :person, class_name: 'Conjugation::Person'
    has_many :user_repetitions, class_name: 'UserRepetition', foreign_key: 'form_id'
  end
end

app/models/conjugation/person.rb
module Conjugation
  class Person < ActiveYaml::Base
  end
end

app/models/conjugation/tense.rb
module Conjugation
  class Tense < ActiveYaml::Base
    extend ActiveHashWhere
  	
  end
end

app/models/conjugation/verb.rb
module Conjugation
  class Verb < ActiveYaml::Base
    extend ActiveHashWhere
  end
end

app/models/personal/exercise_set.rb
class Personal::ExerciseSet < ActiveRecord::Base
  self.table_name = 'personal_exercise_sets'

  serialize :excluded_verbs_ids, Array
  serialize :included_verbs_ids, Array
  serialize :groups, Array
  serialize :tenses_ids, Array

  belongs_to :user
  has_many :user_repetitions, class_name: "UserRepetition", foreign_key: 'personal_exercise_set_id'

  def tenses
    ::Conjugation::Tense.where_in(id: tenses_ids)
  end

  def excluded_verbs
    ::Conjugation::Verb.where_in(id: excluded_verbs_ids)
  end

  def included_verbs
    ::Conjugation::Verb.where_in(id: included_verbs_ids)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :exercise_sets, 
	class_name:  "Personal::ExerciseSet", 
	foreign_key: :user_id

  has_many :user_repetitions,
  class_name: 'UserRepetition',
  foreign_key: :user_id
end

app/models/user_repetition.rb
ActiveRecord::Base.extend ActiveHash::Associations::ActiveRecordExtensions

class UserRepetition < ActiveRecord::Base
  include ::SuperMemo::SM2
  
  belongs_to :user
  belongs_to_active_hash :form, class_name: 'Conjugation::Form', foreign_key: 'form_id'
  belongs_to :exercise_set, class_name: 'Personal::ExerciseSet', foreign_key: 'personal_exercise_set_id'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exercise_settings_controller.rb
class ExerciseSettingsController < ApplicationController
  before_filter :load_context

  def new; end

  def create
    if @context.form.valid?
      ::RandomExercises::SettingsSaver.perform(@context.form.attributes, session)
      redirect_to new_random_exercises_url
    else
      render :new
    end
  end

  def exercise; end

  private

  def load_context
    @context ||= ::RandomExercises::Context.new(params.fetch(:exercise_settings_form, {}))
  end
end

app/controllers/main_page_controller.rb
class MainPageController < ApplicationController
  def index; end
end

app/controllers/personal/exercise_sets_controller.rb
module Personal
  class ExerciseSetsController < ApplicationController
    before_filter :load_context, only: [:new, :index, :create]
    before_filter :get_exercise_set, only: [:train, :check]
    before_filter :load_exercise_context, only: [:train]
    after_filter :load_exercise_context, only: [:check]


    def new; end

    def index; end

    def create
      if @context.form.valid?
        ::Personal::ExerciseSetSaver.perform(current_user, @context.form.attributes)
        redirect_to exercise_sets_path
      else
        render :new
      end
    end

    def train; end

    def check
      form_data = params.fetch(:exercise_form)
      @form = AnswerEvaluationForm.new(form_data)
      @check_answer ||= CheckAnswer.perform(form_data)
      @template_path = @check_answer[:result] ? 'correct_answer' : 'incorrect_answer'
    end

    def save_progress
      form_data = params.fetch(:answer_evaluation_form)
      form = AnswerEvaluationForm.new(form_data)
      if form.valid?
        ur = UserRepetition.find(form.user_repetition_id)
        ur.process_recall_result(form.quality)
      end
      redirect_to train_exercise_sets_path(ur.exercise_set)
    end

    # def edit; end

    # def update; end

    private

    def load_context
      @context = ::Personal::ExerciseSetsContext.new(current_user, params)
    end

    def get_exercise_set
      @exercise_set = current_user.exercise_sets.find(params[:id])
    end

    def load_exercise_context
      @context = ::Personal::ExerciseContext.new(@exercise_set)
    end
  end
end

app/controllers/random_exercise/random_exercises_controller.rb
module RandomExercise
  class RandomExercisesController < ApplicationController

    def new
      @context = ExerciseContext.new(params, session)
    end

    def check
      @form = ::ExerciseForm.new(params.fetch(:exercise_form, {}))
      if check_answer[:result]
        flash[:notice] = t('.notice')
      else
        flash[:error] = t('.error', correct: check_answer[:correct])
      end
      redirect_to new_random_exercises_url
    end

    private

    def check_answer
      @check_answer ||= CheckAnswer.perform(@form.attributes)
    end
  end
end

app/controllers/random_exercises_controller.rb
class RandomExercisesController < ApplicationController
  before_filter :load_form

  def new; end

  def create
    if @form.valid?
      ::RandomExercises::SettingsSaver.perform(@form.attributes, session)
      redirect_to action: 'exercise'
    else
      render :new
    end
  end

  def exercise; end

  private

  def load_form
    @form = ExerciseSettingsForm.new(params.fetch(:exercise_settings_form, {}))
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def reload
    @context ||= ::SectionsContext.new(params.fetch(:exercise_settings_form, {}))
  end
end

app/controllers/verbs_controller.rb
class VerbsController < ApplicationController

  def all
    render json: ::Verbs::Autocomplete.perform(params[:query])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/toastr_helper.rb
module ToastrHelper
  def custom_flash_toastr
    flash_messages = []
    flash.each do |type, message|
      type = 'success' if type == 'notice'
      type = 'error'   if type == 'alert'
      text = "<script>toastr.#{type}('#{message}');</script>"
      flash_messages << text.html_safe if message
    end
    flash_messages.join("\n").html_safe
  end

  def show_errors(errors)
    toastr = []
    errors.each do |error|
      text = "<script>toastr.error('#{error}');</script>"
      toastr << text.html_safe
    end
    toastr.join("\n").html_safe
  end
end

app/views/exercise_settings/elements/_excluded_verbs.html.erb
<%= f.label(:excluded_verbs, class: 'col-sm-2') %>
<div class="col-sm-10" data-source="excluded">
  <%= text_field_tag(:excluded, nil, class: 'x-autocomplete') %>
  <%= f.hidden_field(:excluded_verbs, class: 'x-verbs-hidden') %>
  <div class="x-verbs-result">
	 	<%= render partial: "exercise_settings/elements/verb", collection: presenter.excluded_verbs, as: :verb %>
  </div>
</div>

app/views/exercise_settings/elements/_included_verbs.html.erb
<%= f.label(:included_verbs, class: 'col-sm-2') %>
<div class="col-sm-10" data-source="included">
  <%= text_field_tag(:included, nil, class: 'x-autocomplete') %>
  <%= f.hidden_field(:included_verbs, class: 'x-verbs-hidden') %>
  <div class="x-verbs-result">
	 	<%= render partial: "exercise_settings/elements/verb", collection: presenter.included_verbs, as: :verb %>
  </div>
</div>

app/views/exercise_settings/new.html.erb
<div>
  <%= form_for(@context.form, as: :exercise_settings_form, url: exercise_settings_path) do |f| %>
	  <%= render partial: "/shared/exercise_settings_form/form", locals: { f: f } %>
	<% end %>
</div>

<script>
  $(document).on("page:change", (new ExerciseSettingsForm).init());
</script>

app/views/exercise_settings/reload_section.js.erb
var section = $('<%= @context.presenter.js_class %>');
section.html(
	'<%= j(fields_for(:exercise_settings_form, @context.form) do |f| %>
		<%= render(partial: "exercise_settings/elements/#{@context.presenter.partial}", locals: { f: f, presenter: @context.presenter }) %>
	<% end) %>'
);
(new ExerciseSettingsForm).init();

app/views/main_page/_logged_user.html.erb
<div>
</div>

app/views/main_page/index.html.erb
<h2>Do roboty!</h2>
<%= button_to "Zaloguj się i ćwicz pod kontrolą", "#" %>
<%= button_to "Spróbuj swoich sił w losowych ćwiczeniach", new_exercise_settings_path, method: :get %>

app/views/personal/exercise_sets/check.js.erb
$('.x-overlay').removeClass( "hide" );
$('.x-answer-evaluation').removeClass( "hide" );
$('.x-answer-evaluation').html('<%= j(render partial: "personal/exercise_sets/elements/answer_evaluation", locals: { form: @form }) %>');

app/views/personal/exercise_sets/elements/_answer_evaluation.html.erb
<%= render partial: "personal/exercise_sets/elements/#{@template_path}" %>

Oceń swoją odpowiedź
<br>
<%= form_for(@form, url: save_progress_exercise_sets_path) do |f| %>
	<%= f.hidden_field :user_repetition_id %>
	<br>
	<div>
		<% (1..5).each do |i| %>
			<%= f.label :quality, i %>
		  <%= f.radio_button :quality, i %>
	  <% end %>
	</div>
	<%= f.submit "Zapisz"%>
<% end %>

app/views/personal/exercise_sets/elements/_correct_answer.html.erb
Brawo! Poprawna odpowiedź: <%= @check_answer[:answer] %>

app/views/personal/exercise_sets/elements/_details.html.erb
<li class="list-group-item">	
	<div>
		Zestaw: <strong><%= exercise_set.name %></strong>
		Form do powtórzenia: xxx 
		<!-- TODO : forms to repeat count -->
		<%= link_to "Ćwicz", train_exercise_sets_path(exercise_set) %>
		<%= link_to "Rozwiń", "#", class: "x-show-details", data: { group: exercise_set.id } %>
		<%= link_to "Edytuj", "#" %>
		<%= link_to "Staty", "#" %>
	</div>
	<%= content_tag :div, class: "hide x-details-group-#{exercise_set.id}" do %>
		<p>
			Wybrane czasy:
			<strong><%= presenter.tenses_list(exercise_set) %></strong>
		</p>
		<p>
			Wybrane grupy:
			<strong><%= presenter.groups_list(exercise_set) %></strong>
		</p>

		<p>
			Wykluczone czasowniki:
			<strong><%= presenter.excluded_verbs_list(exercise_set) %></strong>
		</p>

		<p>
			Dodane czasowniki:
			<strong><%= presenter.included_verbs_list(exercise_set) %></strong>
		</p>
	<% end %>
</li>

app/views/personal/exercise_sets/elements/_incorrect_answer.html.erb
Niestety - błędna odpowiedź.
Twoja: <%= @check_answer[:answer] %>
Poprawna: <%= @check_answer[:correct] %>

app/views/personal/exercise_sets/index.html.erb
<h4>Twoje zestawy ćwiczeniowe</h4>

<ul class="list-group">
	<%= render partial: "personal/exercise_sets/elements/details", collection: @context.user_exercise_sets, as: :exercise_set, locals: { presenter: @context.presenter } %>
</ul>

<script>
  $(document).on("page:change", (new ExerciseSetDetails).init());
</script>

app/views/personal/exercise_sets/new.html.erb
<div>
	<%= form_for(@context.form, as: :exercise_settings_form, url: exercise_sets_path) do |f| %>
		<%= f.hidden_field :_personal_set, value: true %>
		<div class="form-group row">
		  <label class="col-sm-2">Nazwa zestawu</label>
	  	<div class="col-sm-10">
				<%= f.text_field :name %>
			</div>
		</div>
	  <%= render partial: "/shared/exercise_settings_form/form", locals: { f: f } %>
	<% end %>
</div>

<script>
  $(document).on("page:change", (new ExerciseSettingsForm).init());
</script>

app/views/personal/exercise_sets/train.html.erb
<div class="hide overlay x-overlay"></div>
<%= render partial: "shared/exercise_form", locals: { context: @context } %>
<div class="display-modal hide x-answer-evaluation"></div>

<script>
  $(document).on("page:change", (new FrenchLetters).init());
</script>

app/views/random_exercise/random_exercises/new.html.erb
<div>
  <% if flash[:notice] %>
    <p class="flash-notice"><%= flash[:notice] %></p>
  <% end %>
  <% if flash[:error] %>
    <p class="flash-error"><%= flash[:error] %></p>
  <% end %>
  <%= form_for(@context.form, url: check_random_exercises_path) do |f| %>
    <%= f.render_errors %>
    <%= f.hidden_field :form_id %>
    <%= f.hidden_field :user_group_id %>
    <br>
    <ul>
      <li>czasownik: <b><%= @context.presenter.verb %></b></li>
      <li>czas: <b><%= @context.presenter.tense %></b></li>
      <li>osoba: <b><%= @context.presenter.person %></b></li>
    </ul>
    <div>
      <%= f.label :answer %>
      <%= f.text_field :answer, class: "x-answer" %>
    </div>

    <div class="x-french-letter">
      <%= render partial: "shared/letter_button", collection: @context.presenter.french_letters, as: :letter %>
    </div>
    <%= f.submit "Sprawdż!" %>
  <% end %>
</div>


<script>
  $(document).on("page:change", (new ExerciseAnswer).init());
</script>

app/views/random_exercises/new.html.erb
<div>
  <%= form_for(@form, url: random_exercises_path) do |f| %>
    <%= f.render_errors %>
    <div class="form-group row">
      <label class="col-sm-1">Czasy gramatyczne</label>
      <div class="col-sm-11">
        <button type="button" class="btn btn-info btn-sm x-check-all-tenses" data-value="false">Zaznacz wszystkie czasy</button>
        <br>
        <div class="x-all-tenses">
          <%= render partial: "random_exercises/elements/labeled_multiple_checkbox", collection: Conjugation::Tense.all, as: :tense, locals: { f: f, key: :tenses } %>
        </div>
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-1">Grupy czasowników</label>
      <div class="col-sm-11">
        <button type="button" class="btn btn-info btn-sm x-check-all-groups" data-value="false">Zaznacz wszystkie grupy</button>
        <br>
        <div class="x-all-groups">
          <%= render partial: "random_exercises/elements/multiple_checkbox", collection: (1..3).to_a, as: :el, locals: { f: f, key: :groups } %>
        </div>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label(:excluded_verbs, class: 'col-sm-1') %>
      <div class="col-sm-11">
        <%= f.text_field(:excluded_verbs) %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label(:included_verbs, class: 'col-sm-1') %>
      <div class="col-sm-11">
        <%= f.text_field(:included_verbs) %>
      </div>
    </div>
    <%= f.submit("Ćwiczenia: start!", class: "btn btn-primary btn-lg btn-block") %>
  <% end %>
</div>

<script>
  $(document).on("page:change", (new ExerciseSettingsForm).init());
</script>

app/views/sections/reload.js.erb
var section = $('<%= @context.presenter.js_class %>');
section.html(
	'<%= j(fields_for(:exercise_settings_form, @context.form) do |f| %>
		<%= render(partial: "/shared/exercise_settings_form/elements/#{@context.presenter.partial}", locals: { f: f, presenter: @context.presenter }) %>
	<% end) %>'
);
(new ExerciseSettingsForm).init();

app/views/shared/_exercise_form.html.erb
<div>
  <% if flash[:notice] %>
    <p class="flash-notice"><%= flash[:notice] %></p>
  <% end %>
  <% if flash[:error] %>
    <p class="flash-error"><%= flash[:error] %></p>
  <% end %>
  <%= form_for(context.form, url: context.submit_path, remote: context.try(:remote?)) do |f| %>
    <%= f.render_errors %>
    <%= f.hidden_field :form_id %>
    <%= f.hidden_field :user_repetition_id %>
    <br>
    <ul>
      <li>czasownik: <b><%= context.presenter.verb %></b></li>
      <li>czas: <b><%= context.presenter.tense %></b></li>
      <li>osoba: <b><%= context.presenter.person %></b></li>
    </ul>
    <div>
      <%= f.label :answer %>
      <%= f.text_field :answer, class: "x-answer" %>
    </div>

    <div class="x-french-letter">
      <%= render partial: "shared/letter_button", collection: context.presenter.french_letters, as: :letter %>
    </div>
    <%= f.submit "Sprawdż!", class: "x-submit" %>
  <% end %>
</div>

app/views/shared/_letter_button.html.erb
<button type="button"><%= letter %></button>

app/views/shared/_show_errors.html.erb
<div class="errors" role="alert">
  <div class="warning">
    <div>
      <% errors.each do |error| %>
        <%= error %> <br>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/exercise_settings_form/elements/_excluded_verbs.html.erb
<%= f.label(:excluded_verbs, class: 'col-sm-2') %>
<div class="col-sm-10" data-source="excluded">
  <%= text_field_tag(:excluded, nil, class: 'x-autocomplete') %>
  <%= f.hidden_field(:excluded_verbs, class: 'x-verbs-hidden') %>
  <div class="x-verbs-result">
	 	<%= render partial: "shared/exercise_settings_form/elements/verb", collection: presenter.excluded_verbs, as: :verb %>
  </div>
</div>

app/views/shared/exercise_settings_form/elements/_included_verbs.html.erb
<%= f.label(:included_verbs, class: 'col-sm-2') %>
<div class="col-sm-10" data-source="included">
  <%= text_field_tag(:included, nil, class: 'x-autocomplete') %>
  <%= f.hidden_field(:included_verbs, class: 'x-verbs-hidden') %>
  <div class="x-verbs-result">
	 	<%= render partial: "shared/exercise_settings_form/elements/verb", collection: presenter.included_verbs, as: :verb %>
  </div>
</div>

app/views/shared/exercise_settings_form/elements/_labeled_multiple_checkbox.html.erb
<span>
  <%= f.check_box(key, { multiple: true, include_hidden: false}, tense.id, nil ) %>
  <%= f.label("#{key}_#{tense.id}", t(tense.symbol)) %>
</span>

app/views/shared/exercise_settings_form/elements/_multiple_checkbox.html.erb
<%= f.check_box(key, { multiple: true, include_hidden: false }, el, nil) %>
<%= f.label("#{key}_#{el}") %>

app/views/shared/exercise_settings_form/elements/_verb.html.erb
<span><%= verb.infinitive %><button class="x-remove-verb" data-id="<%= verb.id %>">X</button></span>